apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Application configuration
  API_TIMEOUT: "30s"
  WORKER_BATCH_SIZE: "100"
  
  # Database configuration
  DB_POOL_SIZE: "10"
  DB_TIMEOUT: "30s"
